#ifndef SOSSY_X_HUTTL_SPRITE_ASSETS_H
#define SOSSY_X_HUTTL_SPRITE_ASSETS_H

#include <stdint.h>

#define FF_SPRITE_TRANSPARENT 0x07e0u
#define FF_ENEMY_TEXTURE_WIDTH 128
#define FF_ENEMY_TEXTURE_HEIGHT 128
#define FF_BEER_TEXTURE_WIDTH 128
#define FF_BEER_TEXTURE_HEIGHT 128
#define FF_FILM_TEXTURE_WIDTH 128
#define FF_FILM_TEXTURE_HEIGHT 128
#define FF_CAMERA_TEXTURE_WIDTH 192
#define FF_CAMERA_TEXTURE_HEIGHT 96

extern const uint16_t g_ff_enemy_texture[FF_ENEMY_TEXTURE_WIDTH * FF_ENEMY_TEXTURE_HEIGHT];
extern const uint16_t g_ff_beer_texture[FF_BEER_TEXTURE_WIDTH * FF_BEER_TEXTURE_HEIGHT];
extern const uint16_t g_ff_film_texture[FF_FILM_TEXTURE_WIDTH * FF_FILM_TEXTURE_HEIGHT];
extern const uint16_t g_ff_camera_texture[FF_CAMERA_TEXTURE_WIDTH * FF_CAMERA_TEXTURE_HEIGHT];

#endif
